# Generated by Django 5.0.7 on 2024-08-27 11:35

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_servicecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_title', models.CharField(max_length=150)),
                ('service_description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('status', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.servicecategory')),
            ],
            options={
                'db_table': 'services',
            },
        ),
    ]
