# Generated by Django 5.0.7 on 2024-08-28 12:57

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_services_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='is_popular',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.CreateModel(
            name='SubServices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_service_title', models.CharField(max_length=150)),
                ('sub_service_description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('selection_type', models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], default='No', max_length=8)),
                ('order', models.SmallIntegerField()),
                ('optional', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5)),
                ('status', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.services')),
            ],
            options={
                'db_table': 'sub_service',
            },
        ),
    ]
