# Generated by Django 5.0.7 on 2024-09-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_services_is_popular_subservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservices',
            name='display_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
