# Generated by Django 5.0.7 on 2024-09-03 09:43

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_alter_subservices_selection_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inspection_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'inspection',
            },
        ),
        migrations.RenameModel(
            old_name='SubServices',
            new_name='SubService',
        ),
        migrations.CreateModel(
            name='SubServiceOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option_type', models.CharField(choices=[('Text Type', 'Text Type'), ('Image Type', 'Image Type')], max_length=20)),
                ('option_title', models.CharField(max_length=150)),
                ('option_description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('order', models.SmallIntegerField()),
                ('status', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_sub_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_sub_service_options', to='adminapp.subservice')),
                ('recommend_inspection_service', models.ManyToManyField(blank=True, to='adminapp.inspection')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_service_option', to='adminapp.subservice')),
            ],
            options={
                'db_table': 'sub_service_option',
            },
        ),
    ]
