# Generated by Django 5.0.7 on 2024-09-06 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_rename_option_image_subserviceoption_option_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subserviceoption',
            name='next_sub_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_sub_service_options', to='adminapp.subservice'),
        ),
    ]
