# Generated by Django 5.0.7 on 2024-09-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='subserviceoption',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
