# Generated by Django 5.0.7 on 2024-10-08 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreferral',
            old_name='refered_email',
            new_name='referred_email',
        ),
    ]
