# Generated by Django 5.0.7 on 2024-09-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_subservice_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
