# Generated by Django 5.0.7 on 2024-11-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_combodetails_comboservicedetails_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combosubservicedetails',
            old_name='service_detail_id',
            new_name='combo_service_id',
        ),
    ]
