# Generated by Django 5.0.7 on 2024-10-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_rename_refered_email_userreferral_referred_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreferral',
            name='referred_register_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userreferral',
            name='redeem_status',
            field=models.CharField(choices=[('Redeemed', 'redeemed'), ('Available', 'available')], default='available', max_length=20),
        ),
    ]
