# Generated by Django 5.0.7 on 2024-11-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_rename_service_detail_id_combosubservicedetails_combo_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='combodetails',
            name='usage_limit',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
