# Generated by Django 5.0.7 on 2024-10-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_userreferral_referred_register_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreferral',
            name='booking_id',
            field=models.IntegerField(blank=True, default='NA'),
        ),
    ]
