# Generated by Django 5.0.7 on 2024-10-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_alter_userreferral_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreferral',
            name='booking_id',
            field=models.CharField(blank=True),
        ),
    ]
