# Generated by Django 5.0.7 on 2024-12-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_rename_combo_comboservicedetails_combo_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combodetails',
            old_name='discount_price',
            new_name='combo_discount_price',
        ),
        migrations.RenameField(
            model_name='combodetails',
            old_name='end_date',
            new_name='combo_end_date',
        ),
        migrations.RenameField(
            model_name='combodetails',
            old_name='name',
            new_name='combo_name',
        ),
        migrations.RenameField(
            model_name='combodetails',
            old_name='price',
            new_name='combo_price',
        ),
        migrations.RenameField(
            model_name='combodetails',
            old_name='start_date',
            new_name='combo_start_date',
        ),
        migrations.RenameField(
            model_name='combodetails',
            old_name='usage_limit',
            new_name='combo_usage_limit',
        ),
    ]
