# Generated by Django 5.0.7 on 2024-10-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_userreferral_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreferral',
            name='referred_email',
            field=models.EmailField(max_length=255),
        ),
    ]
