# Generated by Django 5.0.7 on 2024-12-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_rename_discount_price_combodetails_combo_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combodetails',
            name='discount_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
