# Generated by Django 5.0.7 on 2024-10-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_alter_userreferral_referred_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreferral',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
