# Generated by Django 5.0.7 on 2024-12-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_combodetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combodetails',
            name='status',
            field=models.CharField(blank=True, default='active', null=True),
        ),
    ]
