# Generated by Django 5.0.7 on 2024-12-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_alter_combodetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combodetails',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
