# Generated by Django 5.0.7 on 2024-09-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic_app', '0002_mechanic_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='last_login',
        ),
    ]
