# Generated by Django 5.0.7 on 2024-09-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic_app', '0004_mechanic_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mechanic',
        ),
    ]
