# Generated by Django 5.0.7 on 2024-09-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approved',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default=0, upload_to='mechanic_images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('superadmin', 'superadmin'), ('mechanic', 'mechanic')], default='user', max_length=20),
        ),
    ]
