# Generated by Django 5.0.7 on 2024-10-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='remember_token',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
