# Generated by Django 5.0.7 on 2024-10-25 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingandquote',
            name='car_sub_service',
        ),
        migrations.CreateModel(
            name='SubServiceAndOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_service', models.JSONField(blank=True)),
                ('sub_service_option', models.JSONField(blank=True)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_id', to='user_app.bookingandquote')),
            ],
            options={
                'db_table': 'sub_service_and_option',
            },
        ),
    ]
