# Generated by Django 5.0.7 on 2024-10-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_bookingandquote_car_sub_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subserviceandoption',
            name='sub_service',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='subserviceandoption',
            name='sub_service_option',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
