# Generated by Django 5.0.7 on 2024-09-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_customuser_approved_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default=0, upload_to='profile_images/'),
        ),
    ]
