# Generated by Django 5.0.7 on 2024-09-25 10:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_services_description'),
        ('user_app', '0003_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCarRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vin_number', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_details', to='admin_app.carbrand')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardetails', to='admin_app.carmodel')),
                ('car_trim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_details', to='admin_app.cartrim')),
                ('car_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_details', to='admin_app.caryear')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_car_record',
            },
        ),
    ]
