# Generated by Django 5.0.7 on 2024-10-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_subserviceandoption_sub_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingandquote',
            name='car_services',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subserviceandoption',
            name='sub_service',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subserviceandoption',
            name='sub_service_option',
            field=models.CharField(max_length=500),
        ),
    ]
