# Generated by Django 5.0.7 on 2024-10-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_bookingandquote_car_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingandquote',
            name='carvno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
