# Generated by Django 5.0.7 on 2024-10-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_bookingandquote_carvno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingandquote',
            old_name='carvno',
            new_name='car_vno',
        ),
    ]
