# Generated by Django 5.0.7 on 2024-10-30 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_initial'),
        ('user_app', '0006_rename_carvno_bookingandquote_car_vno'),
    ]

    operations = [
        migrations.AddField(
            model_name='subserviceandoption',
            name='service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_id', to='admin_app.services'),
        ),
    ]
