# Generated by Django 5.0.7 on 2024-10-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_alter_bookingandquote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingandquote',
            name='labour_amount',
            field=models.IntegerField(null=True),
        ),
    ]
