# Generated by Django 5.0.7 on 2024-10-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_bookingandquote_labour_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingandquote',
            name='labour_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bookingandquote',
            name='parts_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bookingandquote',
            name='total_service_amount',
            field=models.FloatField(null=True),
        ),
    ]
