# Generated by Django 5.0.7 on 2024-11-05 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_alter_bookingandquote_labour_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingandquote',
            name='schedule_at',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingandquote',
            name='schedule_time_slot',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Mechanic_leaves',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mechanic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mechanic_leaves',
            },
        ),
    ]
