# Generated by Django 5.0.7 on 2024-11-08 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_initial'),
        ('user_app', '0012_remove_subserviceandoption_sub_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservicebasedoption',
            name='sub_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_service', to='admin_app.subservice'),
        ),
    ]
