# Generated by Django 5.0.7 on 2024-11-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_alter_subservicebasedoption_sub_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingandquote',
            name='car_vno',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
