# Generated by Django 5.0.7 on 2024-11-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_service_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_payment',
            name='payment_mode',
            field=models.CharField(default='cash', max_length=20),
        ),
    ]
