# Generated by Django 5.0.7 on 2024-11-27 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_rename_service_detail_id_combosubservicedetails_combo_service_id'),
        ('user_app', '0018_alter_service_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_combo_package',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_Id', to='admin_app.combodetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_Id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_combo_package',
            },
        ),
    ]
