# Generated by Django 5.0.7 on 2024-11-27 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_rename_service_detail_id_combosubservicedetails_combo_service_id'),
        ('user_app', '0019_user_combo_package'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_combo_package',
            new_name='UserComboPackage',
        ),
    ]
