# Generated by Django 5.0.7 on 2024-11-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0022_usercombopackage_car_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercombopackage',
            name='remaining_combo_usage',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
