# Generated by Django 5.0.7 on 2024-11-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0023_usercombopackage_remaining_combo_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercombopackage',
            name='remaining_combo_usage',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
