# Generated by Django 5.0.7 on 2024-11-28 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_combodetails_usage_limit'),
        ('user_app', '0024_alter_usercombopackage_remaining_combo_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComboTracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_service', to='admin_app.services')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_service_category', to='admin_app.servicecategory')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_service_type', to='admin_app.servicetype')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_sub_service', to='admin_app.subservice')),
            ],
            options={
                'db_table': 'user_combo_tracking',
            },
        ),
    ]
