# Generated by Django 5.0.7 on 2024-11-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0026_usercombotracking_user_combo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercombotracking',
            name='sub_service_option',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usercombotracking',
            name='sub_service',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
