# Generated by Django 5.0.7 on 2024-12-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0027_usercombotracking_sub_service_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingandquote',
            name='booking_type',
            field=models.CharField(default='booking'),
        ),
    ]
