# Generated by Django 5.0.7 on 2024-12-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0028_bookingandquote_booking_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercombopackage',
            old_name='combo',
            new_name='combo_id',
        ),
        migrations.RenameField(
            model_name='usercombopackage',
            old_name='user',
            new_name='user_id',
        ),
    ]
