# Generated by Django 5.0.7 on 2024-12-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0029_rename_combo_usercombopackage_combo_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercombotracking',
            old_name='service_category',
            new_name='service_category_id',
        ),
        migrations.RenameField(
            model_name='usercombotracking',
            old_name='service',
            new_name='service_id',
        ),
        migrations.RenameField(
            model_name='usercombotracking',
            old_name='service_type',
            new_name='service_type_id',
        ),
    ]
