# Generated by Django 5.0.7 on 2024-12-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0030_rename_service_category_usercombotracking_service_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgetPasswordTracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expiration_time', models.DateTimeField()),
            ],
        ),
    ]
