# Generated by Django 5.0.7 on 2024-12-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0032_alter_forgetpasswordtracking_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='forgetpasswordtracking',
            table='forget_password_tracking',
        ),
    ]
