# Generated by Django 5.0.7 on 2024-12-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0033_alter_forgetpasswordtracking_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgetpasswordtracking',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
    ]
