# Generated by Django 5.0.7 on 2024-12-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0034_forgetpasswordtracking_attempt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetpasswordtracking',
            name='attempt_number',
            field=models.IntegerField(),
        ),
    ]
