# Generated by Django 5.0.7 on 2024-12-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0037_membership_customuser_is_prime_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='membership_description',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
