# Generated by Django 5.0.7 on 2024-12-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0038_membership_membership_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='membership_price',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('mechanic', 'mechanic'), ('superadmin', 'superadmin')], default='user', max_length=20),
        ),
    ]
